# Generated by Django 4.1.7 on 2023-02-21 21:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Fundacja', 'Fundacja'), ('Organizacja porządkowa', 'Organizacja pozarządowa'), ('Zbiórka lokalna', 'Zbiórka lokalna')], default='Fundacja', max_length=64)),
                ('categories', models.ManyToManyField(to='website.category')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('address', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Numer telefonu musi składać się z co najmniej 9 cyfr', regex='^\\d{9,}$')])),
                ('city', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Kod pocztowy musi mieć format xx-xxx', regex='^\\d{2}-\\d{3}$')])),
                ('pick_up_date', models.DateTimeField()),
                ('pick_up_time', models.TimeField()),
                ('pick_up_comment', models.CharField(max_length=128)),
                ('categories', models.ManyToManyField(to='website.category')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.institution')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
