# Generated by Django 4.1.7 on 2023-02-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.SmallIntegerField(choices=[('Fundacja', 'Fundacja'), ('Organizacja porządkowa', 'Organizacja pozarządowa'), ('Zbiórka lokalna', 'Zbiórka lokalna')], default='Fundacja', max_length=64),
        ),
    ]
