# Generated by Django 4.1.7 on 2023-03-07 22:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default=uuid.uuid4, max_length=150, unique=None),
        ),
    ]
