# Generated by Django 4.1.7 on 2023-03-08 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_users_options_remove_users_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
